### ISSUE TITLE
Sucessfully ran on Arch Linux

### ISSUE THREAD

**Issue by 1z-z1** [magdesign/Vidifold#27]
I downloaded the requirements and had to specifically place LiberationSans-Regular.ttf in the proper directory as told by ./VIDIFOLD --help

To run it I have to use ./VIDIFOLD --skip-checks

Other than getting a context window saying that I did not have glu, of which I went back, installed, restarted.

**Comment by johnday-github** [comment]
Cool, thanks for sharing,  sorry about the glu thing, I think this was left over from the 3DPlugin, this requirement is removed in v0.34 to be released soon.
